backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Link", name: "link", widget: "string" }
      - {
          label: "Category",
          name: "category",
          widget: "select",
          options:
            [
              "summer-collection",
              "beauty",
              "pc-and-laptops",
              "useful-tools",
              "clothes-and-shoes",
            ],
        }
      - { label: "Image", name: "image", widget: "image" }
